controller_manager:
  ros__parameters:
    update_rate: 100
    # strict_mode: true
    # es read_only?

    # joint_states
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_gripper_controller:
      type: position_controllers/GripperActionController

    left_gripper_controller:
      type: position_controllers/GripperActionController

# JOint state broadcaster
joint_state_broadcaster:
  ros__parameters:
    joints:
    # HEAD
    - torso_head
    
    #RIGHT ARM
    - torso_right_upper_shoulder
    - right_upper_shoulder_lower_shoulder
    - right_lower_shoulder_upper_elbow
    - right_upper_elbow_lower_elbow
    - right_lower_elbow_upper_forearm
    - right_upper_forearm_lower_forearm
    - right_lower_forearm_wrist

    # LEFT ARM
    - torso_left_upper_shoulder
    - left_upper_shoulder_lower_shoulder
    - left_lower_shoulder_upper_elbow
    - left_upper_elbow_lower_elbow
    - left_lower_elbow_upper_forearm
    - left_upper_forearm_lower_forearm
    - left_lower_forearm_wrist

    # RIGHT AND LEFT GRIPPERS
    - r_gripper_l_finger_joint
    - l_gripper_l_finger_joint


# CONTROLLERS
right_arm_controller:
  ros__parameters:
    joints:
      - torso_right_upper_shoulder
      - right_upper_shoulder_lower_shoulder
      - right_lower_shoulder_upper_elbow
      - right_upper_elbow_lower_elbow
      - right_lower_elbow_upper_forearm
      - right_upper_forearm_lower_forearm
      - right_lower_forearm_wrist

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    allow_integration_in_goal_trajectories: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

    # tolerancias para la ejecución de la trayectoria
    torso_right_upper_shoulder:
      trajectory: 0.05
      goal: 0.01
    right_upper_shoulder_lower_shoulder:
      trajectory: 0.05
      goal: 0.01
    right_lower_shoulder_upper_elbow:
      trajectory: 0.05
      goal: 0.01
    right_upper_elbow_lower_elbow:
      trajectory: 0.05
      goal: 0.01
    right_lower_elbow_upper_forearm:
      trajectory: 0.05
      goal: 0.01
    right_upper_forearm_lower_forearm:
      trajectory: 0.05
      goal: 0.01
    right_lower_forearm_wrist:
      trajectory: 0.05
      goal: 0.01


# LEFT ARM TRAJECTORY CONTROLLER
left_arm_controller:
  ros__parameters:
    joints:
      - torso_left_upper_shoulder
      - left_upper_shoulder_lower_shoulder
      - left_lower_shoulder_upper_elbow
      - left_upper_elbow_lower_elbow
      - left_lower_elbow_upper_forearm
      - left_upper_forearm_lower_forearm
      - left_lower_forearm_wrist

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    allow_integration_in_goal_trajectories: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

    # tolerancias para la ejecución de la trayectoria
    torso_left_upper_shoulder:
      trajectory: 0.05
      goal: 0.01
    left_upper_shoulder_lower_shoulder:
      trajectory: 0.05
      goal: 0.01
    left_lower_shoulder_upper_elbow:
      trajectory: 0.05
      goal: 0.01
    left_upper_elbow_lower_elbow:
      trajectory: 0.05
      goal: 0.01
    left_lower_elbow_upper_forearm:
      trajectory: 0.05
      goal: 0.01
    left_upper_forearm_lower_forearm:
      trajectory: 0.05
      goal: 0.01
    left_lower_forearm_wrist:
      trajectory: 0.05
      goal: 0.01


# HEAD CONTROLLER
head_controller:
  ros__parameters:
    joints:
      - torso_head

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

    torso_head:
      trajectory: 0.05
      goal: 0.01


# GRIPPER CONTROLLERS
right_gripper_controller:
  ros__parameters:
    joint: r_gripper_l_finger_joint
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 20.0
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0

left_gripper_controller:
  ros__parameters:
    joint: l_gripper_l_finger_joint
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 20.0
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0