# Goal
# "right" o "left"
string arm
geometry_msgs/Pose target_pose
float64 tolerance
---
# Result
bool success
string message
float64 execution_time
---
# Feedback
float32 progress_percent
# "planning" | "executing" | "done"
string phase